# Generated by Django 3.1.1 on 2020-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuButtonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('button_type', models.CharField(choices=[('callback_data', 'Callback Data'), ('url', 'Link to other resource'), ('switch_inline_query_current_chat', 'Inline Query')], max_length=40)),
                ('button_link', models.CharField(max_length=256)),
            ],
        ),
    ]
