# Generated by Django 3.1.1 on 2020-10-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenubuttonmodel',
            options={'verbose_name': 'Main menu button'},
        ),
    ]
