# Generated by Django 3.1.1 on 2020-10-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0002_auto_20201028_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenubuttonmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Main menu button'},
        ),
    ]
