# Generated by Django 3.1.1 on 2020-10-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0004_auto_20201028_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
