# Generated by Django 3.1.1 on 2020-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0005_eventmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='image_url',
            field=models.URLField(),
        ),
    ]
