# Generated by Django 3.1.1 on 2020-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0006_auto_20201028_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='callback_data',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='mainmenubuttonmodel',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='button_type',
            field=models.CharField(choices=[('callback_data', 'Callback Data'), ('url', 'Link to other resource'), ('switch_inline_query_current_chat', 'Inline Query')], default='callback_data', max_length=40),
        ),
    ]
