# Generated by Django 3.1.1 on 2020-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0007_auto_20201029_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='detail_url',
            field=models.URLField(blank=True),
        ),
    ]
