# Generated by Django 3.1.1 on 2020-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0008_eventmodel_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='detail_url',
            field=models.URLField(),
        ),
    ]
