# Generated by Django 3.1.1 on 2020-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0009_auto_20201029_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='back_button',
            field=models.CharField(default='ofam_events', max_length=30),
        ),
    ]
