# Generated by Django 3.1.1 on 2020-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0010_eventmodel_back_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='button_link',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='button_type',
            field=models.CharField(choices=[('callback_data', 'Callback Data'), ('url', 'Link to other resource'), ('switch_inline_query_current_chat', 'Inline Query')], max_length=40),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
