# Generated by Django 3.1.1 on 2020-10-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0012_exhibitionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='back_button',
            field=models.CharField(default='ofam_events_menu', max_length=30),
        ),
        migrations.AlterField(
            model_name='exhibitionmodel',
            name='back_button',
            field=models.CharField(default='ofam_exhibitions_menu', max_length=30),
        ),
    ]
