# Generated by Django 3.1.1 on 2020-10-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0013_auto_20201030_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='exhibitionmodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mainmenubuttonmodel',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
