# Generated by Django 3.1.1 on 2020-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0014_auto_20201030_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('button_type', models.CharField(choices=[('callback_data', 'Callback Data'), ('url', 'Link to other resource'), ('switch_inline_query_current_chat', 'Inline Query')], max_length=40)),
                ('button_link', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('detail_url', models.URLField()),
                ('image_url', models.URLField()),
                ('back_button', models.CharField(default='ofam_visit_menu', max_length=30)),
            ],
            options={
                'verbose_name': 'Visit',
                'ordering': ['id'],
            },
        ),
    ]
