# Generated by Django 3.1.1 on 2020-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0015_visitmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('button_type', models.CharField(choices=[('callback_data', 'Callback Data'), ('url', 'Link to other resource'), ('switch_inline_query_current_chat', 'Inline Query')], max_length=40)),
                ('button_link', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'OnlineEvent',
                'ordering': ['id'],
            },
        ),
    ]
