# Generated by Django 3.1.1 on 2020-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0016_onlineeventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('link_to_website', models.URLField()),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Shop Product',
                'ordering': ['id'],
            },
        ),
    ]
