# Generated by Django 3.1.1 on 2020-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0017_shopproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineeventmodel',
            name='back_button',
            field=models.CharField(default='back', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineeventmodel',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineeventmodel',
            name='detail_url',
            field=models.URLField(default='detail_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineeventmodel',
            name='image_url',
            field=models.URLField(default='image'),
            preserve_default=False,
        ),
    ]
