# Generated by Django 3.1.1 on 2020-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0018_auto_20201110_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='exhibitionmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mainmenubuttonmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='onlineeventmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
