# Generated by Django 3.1.1 on 2020-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0019_auto_20201111_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('username', models.CharField(max_length=124)),
                ('first_name', models.CharField(max_length=124)),
                ('language_code', models.CharField(max_length=10)),
                ('sticker_message', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Telegram User',
            },
        ),
    ]
