# Generated by Django 3.1.1 on 2020-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0021_auto_20201111_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
