# Generated by Django 3.1.1 on 2020-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0022_auto_20201111_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='sticker_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
