# Generated by Django 3.1.1 on 2020-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0023_auto_20201111_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='button_type',
        ),
        migrations.RemoveField(
            model_name='exhibitionmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='exhibitionmodel',
            name='button_type',
        ),
        migrations.RemoveField(
            model_name='mainmenubuttonmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='mainmenubuttonmodel',
            name='button_type',
        ),
        migrations.RemoveField(
            model_name='onlineeventmodel',
            name='back_button',
        ),
        migrations.RemoveField(
            model_name='onlineeventmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='onlineeventmodel',
            name='button_type',
        ),
        migrations.RemoveField(
            model_name='visitmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='visitmodel',
            name='button_type',
        ),
        migrations.AddField(
            model_name='mainmenubuttonmodel',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenubuttonmodel',
            name='detail_url',
            field=models.URLField(default='detail_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenubuttonmodel',
            name='image_url',
            field=models.URLField(default='image_url'),
            preserve_default=False,
        ),
    ]
