# Generated by Django 3.1.1 on 2020-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0024_auto_20201111_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='detail_url_text',
            field=models.CharField(default='detail_url_text', max_length=32),
        ),
        migrations.AddField(
            model_name='exhibitionmodel',
            name='detail_url_text',
            field=models.CharField(default='detail_url_text', max_length=32),
        ),
        migrations.AddField(
            model_name='mainmenubuttonmodel',
            name='detail_url_text',
            field=models.CharField(default='detail_url_text', max_length=32),
        ),
        migrations.AddField(
            model_name='onlineeventmodel',
            name='detail_url_text',
            field=models.CharField(default='detail_url_text', max_length=32),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='detail_url_text',
            field=models.CharField(default='detail_url_text', max_length=32),
        ),
    ]
