# Generated by Django 3.1.1 on 2020-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0025_auto_20201111_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='detail_url_text',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='exhibitionmodel',
            name='detail_url_text',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mainmenubuttonmodel',
            name='detail_url_text',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='onlineeventmodel',
            name='detail_url_text',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='detail_url_text',
            field=models.CharField(max_length=32),
        ),
    ]
