# Generated by Django 3.1.1 on 2020-11-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0027_auto_20201112_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineEventModel',
        ),
    ]
