# Generated by Django 3.1.1 on 2020-11-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0028_delete_onlineeventmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='back_button',
        ),
        migrations.RemoveField(
            model_name='exhibitionmodel',
            name='back_button',
        ),
        migrations.RemoveField(
            model_name='visitmodel',
            name='back_button',
        ),
    ]
