# Generated by Django 3.1.1 on 2020-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0032_auto_20201127_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['the_order'], 'verbose_name': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='exhibitionmodel',
            options={'ordering': ['the_order'], 'verbose_name': 'Exhibition'},
        ),
        migrations.AlterModelOptions(
            name='mainmenubuttonmodel',
            options={'ordering': ['the_order'], 'verbose_name': 'Main menu button'},
        ),
        migrations.AlterModelOptions(
            name='shopproductmodel',
            options={'ordering': ['the_order'], 'verbose_name': 'Shop Product'},
        ),
        migrations.AlterModelOptions(
            name='visitmodel',
            options={'ordering': ['the_order'], 'verbose_name': 'Visit'},
        ),
        migrations.AddField(
            model_name='shopproductmodel',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
