# Generated by Django 3.1.1 on 2020-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_telegram', '0034_auto_20201127_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='exhibitionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mainmenubuttonmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
