# Generated by Django 3.1.1 on 2020-09-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofam_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Current Exhibition')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('archive', models.BooleanField(default=True)),
            ],
        ),
    ]
